export type ActionType = "goto" | "click" | "fill" | "wait_for" | "use";

export interface ActionTarget {
  selector: string;
  description: string;
}

export interface ExpectSelectorValue {
  selector: string;
  value: string;
}

export interface Expect {
  selector?: string;
  url?: string;
  selector_value?: ExpectSelectorValue;
}

export interface Action {
  id: string;
  type: ActionType;
  target?: ActionTarget;
  value?: string;
  value_ref?: string;
  url?: string;
  /** type=use: id of the fragment to expand inline (E3). */
  use?: string;
  expect?: Expect;
  timeout_ms?: number;
}

/**
 * Trajectory fragment (SPEC-001, component 2): a named, reusable
 * sub-trajectory. Lives versioned in the user's repo (it is curated
 * knowledge), unlike the cache. The plan references { type: "use", use: "<id>" }
 * and the runner expands it inline before executing.
 */
export interface Fragment {
  fragment_id: string;
  description: string;
  /** Documentation of the secrets/parameters (the actions use value_ref ENV:*). */
  params?: Record<string, string>;
  actions: Action[];
  postcondition?: Expect;
}

export interface Plan {
  plan_version: "0.1";
  scenario_id: string;
  task?: string;
  start_url: string;
  generated_by?: { model: string; at: string };
  actions: Action[];
}

export interface Scenario {
  scenario_id: string;
  /**
   * Initial URL. Optional (default "/") and it NEVER needs to be absolute: paths
   * resolve against the effective baseUrl — and --base-url/WINDUP_BASE_URL
   * override the ORIGIN even of absolute URLs (port/host change per
   * environment; the test is the same).
   */
  start_url?: string;
  task: string;
  /** Site-specific knowledge provided by the scenario AUTHOR (doc 07: no hardcoded site knowledge in the engine). */
  hints?: string[];
  /**
   * Prerequisite scenarios (e.g. ["login"]), executed IN THE SAME browser
   * session before this one — each with its own cache/replay. Without an
   * explicit start_url, this scenario CONTINUES from the page where the last
   * dependency ended (and the planner sees that real page).
   */
  depends_on?: string[];
}

export type CacheStatus = "active" | "stale";

export interface CacheEntry {
  cache_version: "0.2";
  key: {
    scenario_id: string;
    start_url: string;
    /** Structural signature of the initial page at plan time (E1). */
    start_sig?: string;
  };
  plan: Plan;
  status: CacheStatus;
  stats: {
    created_at: string;
    last_replayed_at: string | null;
    replay_count: number;
    replay_failures: number;
    /** How many times this scenario's plan has been (re)generated — unstable-scenario detector. */
    plan_generation: number;
  };
}

export type FailureKind = "network" | "verification" | "plan_invalid" | "dependency";

export type CacheOutcome = "hit" | "miss" | "invalidated";

export interface ActionMetrics {
  id: string;
  duration_ms: number;
  verify_ms: number;
  status: "passed" | "failed";
}

export interface RunMetrics {
  scenario_id: string;
  started_at: string;
  cache: CacheOutcome;
  llm_calls: number;
  llm_model: string | null;
  /** Model provider ("google", "openai"); null in replays, absent in pre-0.10 records. */
  llm_provider?: string | null;
  planning_mode: "full" | "incremental" | null;
  /** The planner's semantic retries (doc 03 allows ≤1); null if it did not plan. */
  plan_semantic_retries: number | null;
  /**
   * E1, lenient policy: true if the initial page's sig diverged from the one
   * recorded in the cache (the replay proceeds anyway); null when there was no comparable sig.
   */
  sig_mismatch: boolean | null;
  /** Planning prompt size in chars (E2); null if it did not plan. */
  prompt_chars: number | null;
  tokens: { input: number; output: number };
  estimated_cost_usd: number;
  duration_ms: { total: number; planning: number; execution: number };
  actions: ActionMetrics[];
  result: "passed" | "failed";
  failure: { kind: FailureKind; action_id: string | null; message: string } | null;
  /** Executed plan (diagnostic; absent if generation failed before a plan existed). */
  plan?: Plan;
  /**
   * Post-run summary generated by LLM (`run --summary`, opt-in): what the
   * test did, concrete observed results and difficulties. This call's cost
   * does NOT count toward llm_calls (which measures planning), but adds to
   * estimated_cost_usd.
   */
  summary?: { text: string; model: string; provider: string; tokens: { input: number; output: number }; est_cost_usd: number };
  /** Snapshot (a11y tree) of the page at failure time — diagnostic in the ledger; absent in green runs. */
  failure_snapshot?: string;
  /** Dependencies executed before this scenario (depends_on), in order. */
  dependencies?: Array<{ scenario_id: string; cache: CacheOutcome; llm_calls: number; result: "passed" | "failed"; duration_ms: number }>;
}

export const DEFAULT_TIMEOUT_MS = 5000;
export const MAX_TIMEOUT_MS = 30000;
